#!/bin/bash

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

if [ -f "${POSTGRES_PASSWORD_FILE}" ]; then
    POSTGRES_PASSWORD=$(cat "${POSTGRES_PASSWORD_FILE}")
    export POSTGRES_PASSWORD
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"


wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

exec "$@"
