#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

exec /usr/local/bin/uvicorn config.asgi:application --host 0.0.0.0 --port 5000 --app-dir /app
