# Generated by Django 5.2.7 on 2026-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_rewards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sms_rewards',
            field=models.BooleanField(default=True),
        ),
    ]
