# Generated by Django 5.2.7 on 2026-09-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreferences_email_rewards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.CreateModel(
            name='OneTimeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('magic_link', 'Magic link'), ('sms_otp', 'SMS OTP')], max_length=20)),
                ('target', models.CharField(db_index=True, max_length=255)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['purpose', 'target'], name='users_oneti_purpose_3b16d6_idx')],
            },
        ),
    ]
