# Generated by Django 5.1.4 on 2025-11-02 20:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of customization in dollars (between $99999-$0.01)', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('99999.99')), django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='customizationgroup',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of option in dollars (between $99999-$0.01)', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('99999.99')), django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Amount of ingredient required (e.g., grams, ounces)', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
    ]
