# Generated by Django 5.2.7 on 2025-12-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_last_modified_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationgroup',
            name='maximum_allowed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum allowed'),
        ),
        migrations.AddField(
            model_name='customizationgroup',
            name='minimum_allowed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='minimum allowed'),
        ),
    ]
