# Generated by Django 5.2.7 on 2026-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_customizationgroup_maximum_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_name_138666_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_price_7d229e_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_status_afb747_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_created_3c940b_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_view_co_69a773_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_selecte_4b2a81_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_is_dele_66c315_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_is_feat_02accf_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='audit status'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='audit status'),
        ),
        migrations.AlterField(
            model_name='customizationgroup',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='audit status'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='audit status'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='audit status'),
        ),
    ]
