# Generated by Django 5.1.4 on 2025-06-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationgroup',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='allow_multiple'),
        ),
    ]
