# Generated by Django 5.1.4 on 2025-03-08 16:52

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import navi_backend.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'permissions': [('can_change_status', 'Can change menuitem status'), ('can_feature_product', 'Can mark menuitem as featured'), ('can_view_deleted', 'Can view deleted menuitems')], 'verbose_name': 'MenuItem', 'verbose_name_plural': 'MenuItems'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='body',
            field=models.TextField(default='test', help_text='Detailed menuitem description', verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='featured'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_modified_ip',
            field=models.GenericIPAddressField(editable=False, null=True, verbose_name='last modified IP'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_modified_user_agent',
            field=models.CharField(editable=False, max_length=200, null=True, verbose_name='last modified user agent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='selected_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Count of how many times this menu item was chosen', verbose_name='Selected count'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Internal version tracking', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='View count for product', verbose_name='View count'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this menu item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='orders.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='test', help_text='Short description of menuitem', max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Product image (max 5MB, JPEG/PNG)', upload_to='product_images/%Y/%m/', validators=[navi_backend.core.validators.validate_image_size, navi_backend.core.validators.validate_image_extension], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unqiue name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Price of option in dollars (between $99999-$0.01)', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('99999.990000000005238689482212066650390625')), django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))], verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='orders_menu_name_74ab71_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price'], name='orders_menu_price_865d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['status'], name='orders_menu_status_67d11d_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['created_at'], name='orders_menu_created_36dc22_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['-view_count'], name='orders_menu_view_co_6af855_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['-selected_count'], name='orders_menu_selecte_503963_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_deleted'], name='orders_menu_is_dele_3f870a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_featured', 'status'], name='orders_menu_is_feat_7a6c34_idx'),
        ),
    ]
