# Generated by Django 5.1.4 on 2025-03-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espressomachine',
            old_name='last_maintenance_date',
            new_name='last_maintenance_at',
        ),
        migrations.RemoveField(
            model_name='espressomachine',
            name='last_maintenance_date_time',
        ),
    ]
