# Generated by Django 5.1.4 on 2025-11-02 20:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='ordercustomization',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='ordercustomization',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in dollars (between $99999-$0.01)', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('99999.99')), django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in dollars (between $99999-$0.01)', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('99999.99')), django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Price'),
        ),
    ]
