# Generated by Django 5.1.4 on 2025-06-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customizationgroup_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
