# Generated by Django 5.1.4 on 2025-03-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_last_maintenance_date_espressomachine_last_maintenance_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espressomachine',
            name='last_maintenance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
