# Generated by Django 5.1.4 on 2025-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_category_created_at_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customizationgroup',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercustomization',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(db_index=True, default='test', help_text='Unique name', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
