# Generated by Django 5.2.7 on 2026-05-03 21:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status_alter_ordercustomization_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomization',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in dollars (between $99999-$0.00)', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('99999.99')), django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price'),
        ),
    ]
