# Generated by Django 5.2.7 on 2026-09-03 02:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_machineerrorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points granted per dollar spent on a completed order.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='points per dollar')),
                ('points_per_order', models.PositiveIntegerField(default=0, help_text='Flat bonus points granted for each completed order.', verbose_name='points per order')),
                ('notifications_enabled', models.BooleanField(default=True, help_text="Global kill-switch for award/tier notifications. When off, no notifications are sent regardless of a user's own preference.", verbose_name='notifications enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty settings',
                'verbose_name_plural': 'Loyalty settings',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name', max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='last modified IP')),
                ('last_modified_user_agent', models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or URL for the frontend.', max_length=255, verbose_name='icon')),
                ('rule_type', models.CharField(choices=[('total_points', 'Total points earned'), ('orders_completed', 'Orders completed'), ('total_spent', 'Total amount spent'), ('distinct_items', 'Distinct menu items tried')], db_index=True, help_text='Which metric this award measures.', max_length=32, verbose_name='rule type')),
                ('threshold', models.PositiveIntegerField(help_text='Value of the metric required to earn this award.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='threshold')),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Bonus points granted when this award is earned.', verbose_name='points reward')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_type', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(help_text='Positive to grant, negative to deduct.')),
                ('reason', models.CharField(choices=[('order', 'Order completed'), ('award_bonus', 'Award bonus'), ('adjustment', 'Manual adjustment')], default='order', max_length=32)),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name', max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='last modified IP')),
                ('last_modified_user_agent', models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or URL for the frontend.', max_length=255, verbose_name='icon')),
                ('color', models.CharField(blank=True, default='', help_text='Hex value or design token for the frontend.', max_length=32, verbose_name='color')),
                ('threshold_points', models.PositiveIntegerField(db_index=True, default=0, help_text='Minimum lifetime points required to reach this tier.', verbose_name='threshold points')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Higher rank means a better tier. Used for ordering/upgrades.', verbose_name='rank')),
                ('benefits', models.TextField(blank=True, default='', verbose_name='benefits')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['threshold_points', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='UserLoyalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lifetime_points', models.PositiveIntegerField(default=0, help_text='Total points ever earned. Drives tiers and awards.', verbose_name='lifetime points')),
                ('balance_points', models.PositiveIntegerField(default=0, help_text='Currently spendable points.', verbose_name='balance points')),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total spent')),
                ('notifications_enabled', models.BooleanField(default=True, help_text="User's own opt-in for award/tier notifications.", verbose_name='notifications enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='awards.tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User loyalty',
                'verbose_name_plural': 'User loyalty',
            },
        ),
        migrations.CreateModel(
            name='UserAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='awards.award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'award'), name='unique_user_award')],
            },
        ),
    ]
