# Generated by Django 5.2.7 on 2026-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='rule_type',
            field=models.CharField(choices=[('total_points', 'Total points earned'), ('orders_completed', 'Orders completed'), ('total_spent', 'Total amount spent'), ('distinct_items', 'Distinct menu items tried'), ('customizations', 'Customizations applied')], db_index=True, help_text='Which metric this award measures.', max_length=32, verbose_name='rule type'),
        ),
    ]
