# Generated by Django 5.2.13 on 2026-09-14 01:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_award_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Value of the metric required to earn this award. Leave blank for a multi-level badge and define levels instead.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='threshold'),
        ),
        migrations.CreateModel(
            name='AwardLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(help_text='1 is the first level; higher rank means a better level.', verbose_name='rank')),
                ('name', models.CharField(help_text='Level name shown to the user, e.g. "Bronze".', max_length=100, verbose_name='name')),
                ('threshold', models.PositiveIntegerField(help_text="Value of the award's metric required to reach this level.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='threshold')),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Bonus points granted when this level is reached.', verbose_name='points reward')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or URL for the frontend.', max_length=255, verbose_name='icon')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='awards.award')),
            ],
            options={
                'ordering': ['award', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='useraward',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Highest level reached; empty for single-threshold awards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_by', to='awards.awardlevel'),
        ),
        migrations.AddConstraint(
            model_name='awardlevel',
            constraint=models.UniqueConstraint(fields=('award', 'rank'), name='unique_award_level_rank'),
        ),
    ]
