# Generated by Django 5.2.13 on 2026-09-14 17:37

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_dedupe_order_points'),
        ('menu', '0007_alter_customization_price'),
        ('orders', '0011_alter_machineerrorlog_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltysettings',
            name='points_expiry_days',
            field=models.PositiveIntegerField(default=180, help_text='Spendable points expire after this many days without any points activity. 0 means points never expire.', verbose_name='points expiry (days)'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member behind a manual adjustment or reversal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userloyalty',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time points were earned or spent. Drives expiry.', null=True, verbose_name='last points activity'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(choices=[('order', 'Order completed'), ('award_bonus', 'Award bonus'), ('adjustment', 'Manual adjustment'), ('promotion_bonus', 'Promotion bonus'), ('redemption', 'Reward redeemed'), ('redemption_reversal', 'Reward redemption reversed'), ('expiry', 'Points expired')], default='order', max_length=32),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name', max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='last modified IP')),
                ('last_modified_user_agent', models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Not available before this moment. Blank = no start date.', null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Not available from this moment on. Blank = no end date.', null=True, verbose_name='ends at')),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]), blank=True, default=list, help_text='ISO weekdays it runs on (1 = Monday … 7 = Sunday). Blank = every day.', size=None)),
                ('start_time', models.TimeField(blank=True, help_text='Available from this time each day. Blank = from midnight.', null=True, verbose_name='daily start time')),
                ('end_time', models.TimeField(blank=True, help_text='Available until this time each day. Blank = until midnight.', null=True, verbose_name='daily end time')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('scope', models.CharField(choices=[('menu_item', 'Menu item'), ('category', 'Category'), ('customization', 'Customization'), ('order', 'Whole order')], db_index=True, max_length=16, verbose_name='scope')),
                ('effect', models.CharField(choices=[('multiplier', 'Points multiplier'), ('fixed', 'Fixed bonus points')], max_length=16, verbose_name='effect')),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, help_text='For multiplier promotions, e.g. 2.00 for double points.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='multiplier')),
                ('bonus_points', models.PositiveIntegerField(blank=True, help_text='Fixed promotions: points per qualifying unit (or once per order).', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='bonus points')),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, help_text='Order-scope only: the paid total must be at least this much.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='minimum order total')),
                ('first_order_only', models.BooleanField(default=False, help_text="Order-scope only: applies to the customer's first completed order.", verbose_name='first order only')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='menu.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='menu.customization')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='menu.menuitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='awards.promotion'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name', max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='last modified IP')),
                ('last_modified_user_agent', models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Not available before this moment. Blank = no start date.', null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Not available from this moment on. Blank = no end date.', null=True, verbose_name='ends at')),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]), blank=True, default=list, help_text='ISO weekdays it runs on (1 = Monday … 7 = Sunday). Blank = every day.', size=None)),
                ('start_time', models.TimeField(blank=True, help_text='Available from this time each day. Blank = from midnight.', null=True, verbose_name='daily start time')),
                ('end_time', models.TimeField(blank=True, help_text='Available until this time each day. Blank = until midnight.', null=True, verbose_name='daily end time')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or URL for the frontend.', max_length=255, verbose_name='icon')),
                ('points_cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='points cost')),
                ('max_value', models.DecimalField(decimal_places=2, help_text='The most this reward can take off one unit, in dollars. The customer pays the difference on pricier items.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='maximum value')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='menu.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='menu.customization')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='menu.menuitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField()),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reversed', 'Reversed')], db_index=True, default='applied', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='orders.order')),
                ('order_customization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='orders.ordercustomization')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='orders.orderitem')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='awards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='awards.rewardredemption'),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'order')), fields=('order',), name='unique_order_points_per_order'),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'promotion_bonus')), fields=('order', 'promotion'), name='unique_promotion_bonus_per_order'),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'redemption')), fields=('redemption',), name='unique_debit_per_redemption'),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'redemption_reversal')), fields=('redemption',), name='unique_reversal_per_redemption'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='promotion_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='promotion_end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'menu_item'), ('category__isnull', True), ('customization__isnull', True), ('menu_item__isnull', False)), models.Q(('scope', 'category'), ('category__isnull', False), ('customization__isnull', True), ('menu_item__isnull', True)), models.Q(('scope', 'customization'), ('category__isnull', True), ('customization__isnull', False), ('menu_item__isnull', True)), models.Q(('scope', 'order'), ('category__isnull', True), ('customization__isnull', True), ('menu_item__isnull', True)), _connector='OR'), name='promotion_scope_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bonus_points__isnull', True), ('effect', 'multiplier'), ('multiplier__gt', 1)), models.Q(('bonus_points__gte', 1), ('effect', 'fixed'), ('multiplier__isnull', True)), _connector='OR'), name='promotion_effect_matches_value'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'order'), models.Q(('first_order_only', False), ('min_order_total__isnull', True)), _connector='OR'), name='promotion_order_options_need_order_scope'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='reward_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='reward_end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('customization__isnull', True), ('menu_item__isnull', False)), models.Q(('category__isnull', False), ('customization__isnull', True), ('menu_item__isnull', True)), models.Q(('category__isnull', True), ('customization__isnull', False), ('menu_item__isnull', True)), _connector='OR'), name='reward_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('max_value__gt', 0)), name='reward_max_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('points_cost__gte', 1)), name='reward_points_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='rewardredemption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_customization__isnull', True), ('order_item__isnull', False)), models.Q(('order_customization__isnull', False), ('order_item__isnull', True)), _connector='OR'), name='redemption_exactly_one_line'),
        ),
        migrations.AddConstraint(
            model_name='rewardredemption',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='redemption_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rewardredemption',
            constraint=models.UniqueConstraint(fields=('order_item',), name='unique_redemption_per_order_item'),
        ),
        migrations.AddConstraint(
            model_name='rewardredemption',
            constraint=models.UniqueConstraint(fields=('order_customization',), name='unique_redemption_per_order_customization'),
        ),
    ]
