# Generated by Django 5.1.4 on 2025-08-03 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=50, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Where or what subsystem emitted this log",
                        max_length=32,
                    ),
                ),
                ("recipient", models.IntegerField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="emaillog",
            old_name="reciever",
            new_name="recipient",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="kind",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                help_text="Where or what subsystem emitted this log",
                max_length=32,
            ),
        ),
    ]
