# Generated by Django 5.1.4 on 2025-08-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_textlog_rename_reciever_emaillog_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textlog',
            name='is_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
