# Generated by Django 5.1.4 on 2025-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emaillog_is_sent_textlog_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='error',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textlog',
            name='error',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textlog',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
