# Generated by Django 5.2.7 on 2026-09-03 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_emaillog_error_alter_emaillog_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_emailtemplate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_emailtemplate_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
