# Generated by Django 5.2.7 on 2026-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emailtemplate_created_by_emailtemplate_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlog',
            name='recipient',
            field=models.CharField(max_length=32),
        ),
    ]
