# Generated by Django 5.1.4 on 2025-07-27 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='espressomachine',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espressomachine',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='supported_drinks',
            field=models.ManyToManyField(blank=True, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espressomachine',
            name='machine_type',
            field=models.ForeignKey(blank=True, help_text='Espresso Machine type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espresso_machine', to='devices.machinetype', verbose_name='Machine Type'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='naviport',
            name='espresso_machine',
            field=models.ForeignKey(blank=True, help_text='Espresso Machine attached to this NaviPort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navi_port', to='devices.espressomachine', verbose_name='Espresso Machine'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='naviport',
            name='raspberry_pi',
            field=models.ForeignKey(blank=True, help_text='Raspberry Pi attached to this NaviPort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navi_port', to='devices.raspberrypi', verbose_name='Raspberry Pi'),
        ),
    ]
