# Generated by Django 5.1.4 on 2025-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espressomachine',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='naviport',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='last_modified_user_agent',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='last modified user agent'),
        ),
    ]
