# Generated by Django 5.2.7 on 2025-12-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_espressomachine_last_modified_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='naviport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
