# Generated by Django 5.2.7 on 2025-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_naviport_latitude_naviport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviport',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 3'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='naviport',
            name='state_or_region',
            field=models.CharField(blank=True, max_length=255, verbose_name='State or region'),
        ),
    ]
