# Generated by Django 5.2.7 on 2026-02-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_espressomachine_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espressomachine',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='naviport',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Draft'), ('R', 'Archived')], db_index=True, default='A', help_text='availability status', max_length=1, verbose_name='status'),
        ),
    ]
