# Generated by Django 5.2.7 on 2026-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_espressomachine_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='device_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
