# Generated by Django 5.2.13 on 2026-09-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_raspberrypi_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
