#!/bin/sh
# This script starts the Celery beat scheduler for local development with debug logging.
exec celery -A config.celery beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
