# Generated by Django 5.1.4 on 2025-07-27 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_modified_ip",
                    models.GenericIPAddressField(
                        editable=False, null=True, verbose_name="last modified IP"
                    ),
                ),
                (
                    "last_modified_user_agent",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        null=True,
                        verbose_name="last modified user agent",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_capture", "Requires Capture"),
                            ("succeeded", "Succeeded"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
