# Generated by Django 5.2.13 on 2026-09-20 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_raspberrypi_device_token'),
        ('payments', '0008_payment_stripe_payment_method_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectiveTaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('navi_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='devices.naviport')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('navi_port', 'effective_date')},
            },
        ),
    ]
